baseURL = 'https://log.woodweb.ca/'
languageCode = 'en-us'
title = 'Wood Wide Log'
copyright = "Daniel McCarney"
enableEmoji = true
theme = "archie"
#enableGitInfo = true

[markup]
  [markup.highlight]
    style = 'monokai'
    tabwidth = 2
  [markup.goldmark.renderer]
    unsafe = false
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1

[params]
  description = "An attempt at a journal slash dev log by @cpu."
  customcss = ["css/custom.css"]
  images = ["/2022/10/wwl/crow.small.jpg"]
  mainSections = [ "log" ]

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/cpu/woodwidelog"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/cpu/"

[permalinks]
  posts = '/:year/:month/:title'

[[menu.main]]
  name = "Log"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Articles"
  url = "/articles"
  weight = 2

[[menu.main]]
  name = "Archive"
  url = "/posts"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 4
