name: Deploy to GH pages

on:
  push:
  pull_request:

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nix Flakes doesn't work on shallow clones

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Build static site
        run: nix build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: result
          cname: log.woodweb.ca
